#!/usr/bin/env node
/**
 * Sample API for testing the Bring Your Own API (BYOAPI) flow.
 *
 * ───────────────────────────────────────────────────────────────
 * What this is
 * ───────────────────────────────────────────────────────────────
 * A self-contained Node.js HTTP server (no deps) that serves a
 * realistic-ish merchant/ecommerce API. It's designed so you can
 * point the BYOAPI flow at it, let the LLM extract the endpoints,
 * and have the planner build dashboards against real HTTP calls.
 *
 * ───────────────────────────────────────────────────────────────
 * How to use
 * ───────────────────────────────────────────────────────────────
 *   # 1. Start the sample API in one terminal:
 *   node scripts/sample-api.mjs
 *   # → "Sample API listening on http://127.0.0.1:49200"
 *
 *   # 2. Start the dev server in another:
 *   npm run dev
 *
 *   # 3. In the app:
 *   #   a. Click ＋ Connect data → API keys → "+ New key"
 *   #      Name:  sample_demo
 *   #      Value: Bearer demo-key-12345
 *   #      (this is the value the /v1/account/me endpoint
 *   #       checks for; it's documented in the file below)
 *   #
 *   #   b. Click ＋ Connect data → API
 *   #      Name:        SampleStore
 *   #      Base URL:    http://localhost:49200
 *   #      Auth:        Use a saved key → sample_demo
 *   #      Sample:      paste any of the example responses below
 *   #
 *   #   c. Click "Register API". The LLM extracts ~8 endpoints
 *   #      from your sample. Each becomes a planner capability
 *   #      named user.sample_store.<endpoint_name>.
 *   #
 *   #   d. Try the planner with intents like:
 *   #        "Show me daily revenue for the last 30 days"
 *   #        "Which products are low on stock?"
 *   #        "Top 5 customers by lifetime spend"
 *
 * ───────────────────────────────────────────────────────────────
 * Endpoints
 * ───────────────────────────────────────────────────────────────
 *   GET /v1/products                 list all products
 *   GET /v1/products/{id}            product details + total sold
 *   GET /v1/orders                   recent orders (limit=20)
 *   GET /v1/orders/recent            most recent 20 orders
 *   GET /v1/customers/top            top customers by lifetime spend
 *                                    (?limit=10)
 *   GET /v1/revenue/series           daily revenue series
 *                                    (?days=30)
 *   GET /v1/inventory/low-stock      products below threshold
 *                                    (?threshold=20)
 *   GET /v1/account/me               current user (AUTH REQUIRED)
 *                                    expects "Authorization: Bearer
 *                                    demo-key-12345"
 *   GET /health                      liveness check (no auth)
 *
 * ───────────────────────────────────────────────────────────────
 * Configuration
 * ───────────────────────────────────────────────────────────────
 *   PORT             default 49200
 *   SAMPLE_API_KEY   default "Bearer demo-key-12345"
 *                    (the value the /v1/account/me endpoint checks)
 *
 * ───────────────────────────────────────────────────────────────
 * Determinism
 * ───────────────────────────────────────────────────────────────
 * All data is generated by a seeded mulberry32 PRNG so every run
 * produces the same numbers. Useful for screenshots and tests.
 */
import { createHash } from "node:crypto";
import http from "node:http";
import { URL } from "node:url";

const PORT = parseInt(process.env.PORT ?? "49200", 10);
const API_KEY = process.env.SAMPLE_API_KEY ?? "Bearer demo-key-12345";
const HOST = "127.0.0.1";

// ───────── deterministic RNG (mulberry32) ─────────
function rng(seed) {
  let t = seed >>> 0;
  return () => {
    t = (t + 0x6D2B79F5) >>> 0;
    let r = t;
    r = Math.imul(r ^ (r >>> 15), r | 1);
    r ^= r + Math.imul(r ^ (r >>> 7), r | 61);
    return ((r ^ (r >>> 14)) >>> 0) / 4294967296;
  };
}
const seed = (s) => {
  const h = createHash("sha256").update(s).digest();
  return h.readUInt32BE(0);
};
const pick = (rand, arr) => arr[Math.floor(rand() * arr.length)];
const rint = (rand, lo, hi) => Math.floor(rand() * (hi - lo + 1)) + lo;

// ───────── fixtures ─────────
const CATEGORIES = [
  { name: "mains",   basePrice: 28, margin: 0.55 },
  { name: "sides",   basePrice: 8,  margin: 0.65 },
  { name: "drinks",  basePrice: 4,  margin: 0.75 },
  { name: "dessert", basePrice: 6,  margin: 0.70 },
  { name: "merch",   basePrice: 22, margin: 0.50 },
];

const FIRST = ["Ada", "Marcus", "Lila", "Theo", "Yui", "Omar", "Priya", "Bao", "Noor", "Cyrus", "Iris", "Felix", "Maya", "Diego", "Sana", "Ren", "Vega", "Hana", "Quinn", "Mateo"];
const LAST  = ["Okafor", "Chen", "Patel", "Rivera", "Kim", "Singh", "Nguyen", "Garcia", "Brown", "Lee", "Hassan", "Park", "Lopez", "Schmidt", "Tanaka", "Reed", "Khan", "Mendez", "Wong", "Volkov"];

// Generate 20 products across 5 categories.
const products = [];
{
  const rand = rng(seed("products"));
  for (let i = 0; i < 20; i++) {
    const cat = CATEGORIES[i % CATEGORIES.length];
    const id = `p_${String(i + 1).padStart(3, "0")}`;
    const variants = ["Classic", "Spicy", "Smoked", "Sweet", "House", "Limited", "Family", "Single"];
    products.push({
      id,
      name: `${pick(rand, variants)} ${cat.name === "merch" ? "tee" : cat.name === "drinks" ? "draft" : "plate"}`,
      category: cat.name,
      price: Math.round(cat.basePrice * (0.85 + rand() * 0.45) * 100) / 100,
      inStock: rint(rand, 5, 240),
    });
  }
}

// Generate 50 customers with lifetime spend + last-order dates.
const customers = [];
{
  const rand = rng(seed("customers"));
  for (let i = 0; i < 50; i++) {
    const first = pick(rand, FIRST);
    const last = pick(rand, LAST);
    customers.push({
      id: `c_${String(i + 1).padStart(3, "0")}`,
      name: `${first} ${last}`,
      email: `${first.toLowerCase()}.${last.toLowerCase()}@example.com`,
      segment: pick(rand, ["vip", "regular", "new", "lapsed"]),
      lifetimeSpend: Math.round(rand() * 4800 + 50),
      orders: rint(rand, 1, 42),
      lastOrder: new Date(Date.now() - rint(rand, 1, 60) * 86_400_000).toISOString().slice(0, 10),
    });
  }
}

// Generate 30 days of orders, 5-12 per day, deterministic per (day, slot).
const orders = [];
const dailyRevenue = [];
{
  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);
  for (let d = 0; d < 30; d++) {
    const day = new Date(today.getTime() - d * 86_400_000);
    const date = day.toISOString().slice(0, 10);
    const rand = rng(seed(`day-${date}`));
    const count = rint(rand, 5, 12);
    let dayTotal = 0;
    for (let s = 0; s < count; s++) {
      const itemCount = rint(rand, 1, 4);
      const items = [];
      let orderTotal = 0;
      for (let k = 0; k < itemCount; k++) {
        const p = pick(rand, products);
        const qty = rint(rand, 1, 3);
        items.push({ productId: p.id, name: p.name, price: p.price, qty });
        orderTotal += p.price * qty;
      }
      const customer = pick(rand, customers);
      const status = pick(rand, ["paid", "paid", "paid", "refunded", "pending"]);
      orders.push({
        id: `o_${date}_${String(s + 1).padStart(2, "0")}`,
        date,
        customerId: customer.id,
        customerName: customer.name,
        items,
        total: Math.round(orderTotal * 100) / 100,
        status,
      });
      if (status === "paid") dayTotal += orderTotal;
    }
    dailyRevenue.push({
      date,
      orders: count,
      paidOrders: orders.filter((o) => o.date === date && o.status === "paid").length,
      revenue: Math.round(dayTotal * 100) / 100,
    });
  }
}
dailyRevenue.reverse(); // oldest first

// Per-product totals (for the /v1/products/{id} response).
const productStats = new Map();
for (const o of orders) {
  if (o.status !== "paid") continue;
  for (const it of o.items) {
    const cur = productStats.get(it.productId) ?? { unitsSold: 0, revenue: 0 };
    cur.unitsSold += it.qty;
    cur.revenue += it.qty * it.price;
    productStats.set(it.productId, cur);
  }
}

// ───────── HTTP server ─────────
function json(res, status, body) {
  const text = JSON.stringify(body);
  res.writeHead(status, {
    "Content-Type": "application/json; charset=utf-8",
    "Content-Length": Buffer.byteLength(text).toString(),
    "Access-Control-Allow-Origin": "*",
  });
  res.end(text);
}

function notFound(res, path) {
  json(res, 404, { error: "not_found", path, hint: "Try GET /health for the endpoint list." });
}

const server = http.createServer((req, res) => {
  const started = Date.now();
  const url = new URL(req.url ?? "/", `http://${HOST}:${PORT}`);
  const path = url.pathname;
  const method = req.method ?? "GET";

  // CORS preflight.
  if (method === "OPTIONS") {
    res.writeHead(204, {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Authorization, Content-Type",
    });
    res.end();
    return;
  }

  // Health/discovery.
  if (path === "/health") {
    return json(res, 200, {
      ok: true,
      endpoints: [
        "GET /v1/products",
        "GET /v1/products/{id}",
        "GET /v1/orders",
        "GET /v1/orders/recent",
        "GET /v1/customers/top",
        "GET /v1/revenue/series?days=30",
        "GET /v1/inventory/low-stock?threshold=20",
        "GET /v1/account/me  (Authorization: Bearer demo-key-12345)",
      ],
    });
  }

  // Auth gate for /v1/account/me.
  if (path === "/v1/account/me") {
    if (req.headers.authorization !== API_KEY) {
      res.writeHead(401, {
        "Content-Type": "application/json",
        "WWW-Authenticate": 'Bearer realm="sample-api"',
        "Access-Control-Allow-Origin": "*",
      });
      res.end(JSON.stringify({ error: "unauthorized" }));
      log(method, path, 401, started);
      return;
    }
    return json(res, 200, {
      id: "u_001",
      name: "Demo Account",
      role: "owner",
      plan: "pro",
      email: "demo@example.com",
      createdAt: "2024-03-15T10:00:00.000Z",
    });
  }

  // Open endpoints.
  if (path === "/v1/products" && method === "GET") {
    return json(res, 200, { products });
  }
  const productMatch = path.match(/^\/v1\/products\/([A-Za-z0-9_]+)$/);
  if (productMatch && method === "GET") {
    const p = products.find((x) => x.id === productMatch[1]);
    if (!p) return notFound(res, path);
    const stats = productStats.get(p.id) ?? { unitsSold: 0, revenue: 0 };
    return json(res, 200, { ...p, unitsSold: stats.unitsSold, revenue: Math.round(stats.revenue * 100) / 100 });
  }
  if (path === "/v1/orders/recent" && method === "GET") {
    const recent = [...orders]
      .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0))
      .slice(0, 20);
    return json(res, 200, { orders: recent });
  }
  if (path === "/v1/orders" && method === "GET") {
    const limit = Math.min(parseInt(url.searchParams.get("limit") ?? "20", 10) || 20, 100);
    return json(res, 200, { orders: orders.slice(0, limit) });
  }
  if (path === "/v1/customers/top" && method === "GET") {
    const limit = Math.min(parseInt(url.searchParams.get("limit") ?? "10", 10) || 10, 50);
    const top = [...customers]
      .sort((a, b) => b.lifetimeSpend - a.lifetimeSpend)
      .slice(0, limit);
    return json(res, 200, { customers: top });
  }
  if (path === "/v1/revenue/series" && method === "GET") {
    const days = Math.min(parseInt(url.searchParams.get("days") ?? "30", 10) || 30, 90);
    return json(res, 200, { days, series: dailyRevenue.slice(-days) });
  }
  if (path === "/v1/inventory/low-stock" && method === "GET") {
    const threshold = parseInt(url.searchParams.get("threshold") ?? "20", 10) || 20;
    const low = products
      .filter((p) => p.inStock < threshold)
      .map((p) => ({
        id: p.id,
        name: p.name,
        category: p.category,
        inStock: p.inStock,
        threshold,
      }))
      .sort((a, b) => a.inStock - b.inStock);
    return json(res, 200, { threshold, count: low.length, products: low });
  }

  return notFound(res, path);

  function log(method, path, status, started) {
    const ms = Date.now() - started;
    // eslint-disable-next-line no-console
    console.log(`${method.padEnd(6)} ${path}  ${status}  ${ms}ms`);
  }
});

server.listen(PORT, HOST, () => {
  // eslint-disable-next-line no-console
  console.log(`Sample API listening on http://${HOST}:${PORT}`);
  // eslint-disable-next-line no-console
  console.log(`Auth key (for /v1/account/me): ${API_KEY}`);
  // eslint-disable-next-line no-console
  console.log(`Try: curl http://${HOST}:${PORT}/health`);
});

const shutdown = () => {
  // eslint-disable-next-line no-console
  console.log("\nShutting down…");
  server.close(() => process.exit(0));
  setTimeout(() => process.exit(1), 2000).unref();
};
process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);
